// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/geo/geo.proto

package geo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for GeoLocation service

func NewGeoLocationEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for GeoLocation service

type GeoLocationService interface {
	ReportGeo(ctx context.Context, in *ReportRequest, opts ...client.CallOption) (*ReportResponse, error)
	QueryGeo(ctx context.Context, in *QueryRequest, opts ...client.CallOption) (*QueryResponse, error)
}

type geoLocationService struct {
	c    client.Client
	name string
}

func NewGeoLocationService(name string, c client.Client) GeoLocationService {
	return &geoLocationService{
		c:    c,
		name: name,
	}
}

func (c *geoLocationService) ReportGeo(ctx context.Context, in *ReportRequest, opts ...client.CallOption) (*ReportResponse, error) {
	req := c.c.NewRequest(c.name, "GeoLocation.ReportGeo", in)
	out := new(ReportResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLocationService) QueryGeo(ctx context.Context, in *QueryRequest, opts ...client.CallOption) (*QueryResponse, error) {
	req := c.c.NewRequest(c.name, "GeoLocation.QueryGeo", in)
	out := new(QueryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GeoLocation service

type GeoLocationHandler interface {
	ReportGeo(context.Context, *ReportRequest, *ReportResponse) error
	QueryGeo(context.Context, *QueryRequest, *QueryResponse) error
}

func RegisterGeoLocationHandler(s server.Server, hdlr GeoLocationHandler, opts ...server.HandlerOption) error {
	type geoLocation interface {
		ReportGeo(ctx context.Context, in *ReportRequest, out *ReportResponse) error
		QueryGeo(ctx context.Context, in *QueryRequest, out *QueryResponse) error
	}
	type GeoLocation struct {
		geoLocation
	}
	h := &geoLocationHandler{hdlr}
	return s.Handle(s.NewHandler(&GeoLocation{h}, opts...))
}

type geoLocationHandler struct {
	GeoLocationHandler
}

func (h *geoLocationHandler) ReportGeo(ctx context.Context, in *ReportRequest, out *ReportResponse) error {
	return h.GeoLocationHandler.ReportGeo(ctx, in, out)
}

func (h *geoLocationHandler) QueryGeo(ctx context.Context, in *QueryRequest, out *QueryResponse) error {
	return h.GeoLocationHandler.QueryGeo(ctx, in, out)
}
