// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/passanger/passanger.proto

package passanger

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "github.com/micro/go-micro/v2/api/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Passanger service

func NewPassangerEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Passanger service

type PassangerService interface {
	Call(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error)
	GetLocation(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error)
}

type passangerService struct {
	c    client.Client
	name string
}

func NewPassangerService(name string, c client.Client) PassangerService {
	return &passangerService{
		c:    c,
		name: name,
	}
}

func (c *passangerService) Call(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error) {
	req := c.c.NewRequest(c.name, "Passanger.Call", in)
	out := new(proto1.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passangerService) GetLocation(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error) {
	req := c.c.NewRequest(c.name, "Passanger.GetLocation", in)
	out := new(proto1.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Passanger service

type PassangerHandler interface {
	Call(context.Context, *proto1.Request, *proto1.Response) error
	GetLocation(context.Context, *proto1.Request, *proto1.Response) error
}

func RegisterPassangerHandler(s server.Server, hdlr PassangerHandler, opts ...server.HandlerOption) error {
	type passanger interface {
		Call(ctx context.Context, in *proto1.Request, out *proto1.Response) error
		GetLocation(ctx context.Context, in *proto1.Request, out *proto1.Response) error
	}
	type Passanger struct {
		passanger
	}
	h := &passangerHandler{hdlr}
	return s.Handle(s.NewHandler(&Passanger{h}, opts...))
}

type passangerHandler struct {
	PassangerHandler
}

func (h *passangerHandler) Call(ctx context.Context, in *proto1.Request, out *proto1.Response) error {
	return h.PassangerHandler.Call(ctx, in, out)
}

func (h *passangerHandler) GetLocation(ctx context.Context, in *proto1.Request, out *proto1.Response) error {
	return h.PassangerHandler.GetLocation(ctx, in, out)
}
