// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: lbs.proto

package lbs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Lbs service

func NewLbsEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Lbs service

type LbsService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Lbs_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Lbs_PingPongService, error)
}

type lbsService struct {
	c    client.Client
	name string
}

func NewLbsService(name string, c client.Client) LbsService {
	return &lbsService{
		c:    c,
		name: name,
	}
}

func (c *lbsService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Lbs.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lbsService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Lbs_StreamService, error) {
	req := c.c.NewRequest(c.name, "Lbs.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &lbsServiceStream{stream}, nil
}

type Lbs_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type lbsServiceStream struct {
	stream client.Stream
}

func (x *lbsServiceStream) Close() error {
	return x.stream.Close()
}

func (x *lbsServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *lbsServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *lbsServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *lbsServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *lbsService) PingPong(ctx context.Context, opts ...client.CallOption) (Lbs_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Lbs.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &lbsServicePingPong{stream}, nil
}

type Lbs_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type lbsServicePingPong struct {
	stream client.Stream
}

func (x *lbsServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *lbsServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *lbsServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *lbsServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *lbsServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *lbsServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Lbs service

type LbsHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Lbs_StreamStream) error
	PingPong(context.Context, Lbs_PingPongStream) error
}

func RegisterLbsHandler(s server.Server, hdlr LbsHandler, opts ...server.HandlerOption) error {
	type lbs interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Lbs struct {
		lbs
	}
	h := &lbsHandler{hdlr}
	return s.Handle(s.NewHandler(&Lbs{h}, opts...))
}

type lbsHandler struct {
	LbsHandler
}

func (h *lbsHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.LbsHandler.Call(ctx, in, out)
}

func (h *lbsHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.LbsHandler.Stream(ctx, m, &lbsStreamStream{stream})
}

type Lbs_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type lbsStreamStream struct {
	stream server.Stream
}

func (x *lbsStreamStream) Close() error {
	return x.stream.Close()
}

func (x *lbsStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *lbsStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *lbsStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *lbsStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *lbsHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.LbsHandler.PingPong(ctx, &lbsPingPongStream{stream})
}

type Lbs_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type lbsPingPongStream struct {
	stream server.Stream
}

func (x *lbsPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *lbsPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *lbsPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *lbsPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *lbsPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *lbsPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
