// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/lbs.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for LBSSrv service

func NewLBSSrvEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for LBSSrv service

type LBSSrvService interface {
	DriverLocations(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type lBSSrvService struct {
	c    client.Client
	name string
}

func NewLBSSrvService(name string, c client.Client) LBSSrvService {
	return &lBSSrvService{
		c:    c,
		name: name,
	}
}

func (c *lBSSrvService) DriverLocations(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "LBSSrv.DriverLocations", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LBSSrv service

type LBSSrvHandler interface {
	DriverLocations(context.Context, *Request, *Response) error
}

func RegisterLBSSrvHandler(s server.Server, hdlr LBSSrvHandler, opts ...server.HandlerOption) error {
	type lBSSrv interface {
		DriverLocations(ctx context.Context, in *Request, out *Response) error
	}
	type LBSSrv struct {
		lBSSrv
	}
	h := &lBSSrvHandler{hdlr}
	return s.Handle(s.NewHandler(&LBSSrv{h}, opts...))
}

type lBSSrvHandler struct {
	LBSSrvHandler
}

func (h *lBSSrvHandler) DriverLocations(ctx context.Context, in *Request, out *Response) error {
	return h.LBSSrvHandler.DriverLocations(ctx, in, out)
}
